name: logsync-receiver
base: core18
version: '0.2'
summary: Run receiving server for http/https logs
description: |
  Simple example snap to show how to receive journal messages from a device
  on a remote journal server.

  Currently only the http (not https!) protocol is supported, this will soon
  be extended.

  Log files can be found in /var/snap/logsync-receiver/current/
  And can be read with:

  sudo journalctl -f -D /var/snap/logsync-receiver/current/

grade: stable
confinement: strict

layout:
  /etc/systemd:
    bind: $SNAP_DATA/systemd

apps:
  remote:
    command: lib/systemd/systemd-journal-remote --listen-http=-3 --output=$SNAP_DATA
    plugs:
      - network-bind
      - network
      - time-control # this quietens log spam at access of /proc/1/environ
    daemon: simple
    sockets:
      systemd-journal-remote:
        listen-stream: 19532

parts:
  remote:
    plugin: nil
    stage-packages:
      - systemd-journal-remote
